In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-disease-prediction-using-logistic-regression/framingham.csv


In [2]:
df=pd.read_csv('/kaggle/input/heart-disease-prediction-using-logistic-regression/framingham.csv')

In [3]:
df

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4233       66.0     86.0           1  
4234       65.0     68.0           0  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  

[4238 rows x 16 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4238 non-null   int64  
 1   age              4238 non-null   int64  
 2   education        4133 non-null   float64
 3   currentSmoker    4238 non-null   int64  
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4185 non-null   float64
 6   prevalentStroke  4238 non-null   int64  
 7   prevalentHyp     4238 non-null   int64  
 8   diabetes         4238 non-null   int64  
 9   totChol          4188 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4219 non-null   float64
 13  heartRate        4237 non-null   float64
 14  glucose          3850 non-null   float64
 15  TenYearCHD       4238 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 529.9 KB


In [5]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [6]:
df=df.dropna()

In [7]:
df.isnull().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [8]:
df.describe()

male          age    education  currentSmoker   cigsPerDay  \
count  3656.000000  3656.000000  3656.000000    3656.000000  3656.000000   
mean      0.443654    49.557440     1.979759       0.489059     9.022155   
std       0.496883     8.561133     1.022657       0.499949    11.918869   
min       0.000000    32.000000     1.000000       0.000000     0.000000   
25%       0.000000    42.000000     1.000000       0.000000     0.000000   
50%       0.000000    49.000000     2.000000       0.000000     0.000000   
75%       1.000000    56.000000     3.000000       1.000000    20.000000   
max       1.000000    70.000000     4.000000       1.000000    70.000000   

            BPMeds  prevalentStroke  prevalentHyp     diabetes      totChol  \
count  3656.000000      3656.000000   3656.000000  3656.000000  3656.000000   
mean      0.030361         0.005744      0.311543     0.027079   236.873085   
std       0.171602         0.075581      0.463187     0.162335    44.096223   
min       0.000000         0.000000      0.000000     0.000000   113.000000   
25%       0.000000         0.000000      0.000000     0.000000   206.000000   
50%       0.000000         0.000000      0.000000     0.000000   234.000000   
75%       0.000000         0.000000      1.000000     0.000000   263.250000   
max       1.000000         1.000000      1.000000     1.000000   600.000000   

             sysBP        diaBP          BMI    heartRate      glucose  \
count  3656.000000  3656.000000  3656.000000  3656.000000  3656.000000   
mean    132.368025    82.912062    25.784185    75.730580    81.856127   
std      22.092444    11.974825     4.065913    11.982952    23.910128   
min      83.500000    48.000000    15.540000    44.000000    40.000000   
25%     117.000000    75.000000    23.080000    68.000000    71.000000   
50%     128.000000    82.000000    25.380000    75.000000    78.000000   
75%     144.000000    90.000000    28.040000    82.000000    87.000000   
max     295.000000   142.500000    56.800000   143.000000   394.000000   

        TenYearCHD  
count  3656.000000  
mean      0.152352  
std       0.359411  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000

In [9]:
x=df.iloc[:,:15]
y=df.iloc[:,-1]

In [10]:
x

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4231     1   58        3.0              0         0.0     0.0   
4232     1   68        1.0              0         0.0     0.0   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4231                0             1         0    187.0  141.0   81.0  24.96   
4232                0             1         0    176.0  168.0   97.0  23.14   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  
0          80.0     77.0  
1          95.0     76.0  
2          75.0     70.0  
3          65.0    103.0  
4          85.0     85.0  
...         ...      ...  
4231       80.0     81.0  
4232       60.0     79.0  
4233       66.0     86.0  
4234       65.0     68.0  
4237       80.0    107.0  

[3656 rows x 15 columns]

In [11]:
y

0       0
1       0
2       0
3       1
4       0
       ..
4231    0
4232    1
4233    1
4234    0
4237    0
Name: TenYearCHD, Length: 3656, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [13]:
x_train

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
2545     0   48        4.0              0         0.0     0.0   
1154     0   45        2.0              0         0.0     0.0   
1538     0   45        4.0              0         0.0     0.0   
1407     0   42        1.0              0         0.0     0.0   
4070     0   40        3.0              0         0.0     0.0   
...    ...  ...        ...            ...         ...     ...   
3223     0   50        2.0              1        20.0     0.0   
1040     1   58        1.0              1        20.0     0.0   
1266     1   58        1.0              0         0.0     0.0   
264      1   57        1.0              0         0.0     0.0   
1225     1   40        1.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
2545                0             0         0    240.0  123.0   80.0  24.57   
1154                0             1         0    222.0  167.0  107.0  25.56   
1538                0             0         0    220.0  108.0   81.0  25.68   
1407                0             0         0    170.0  113.0   79.0  21.31   
4070                0             1         0    202.0  158.0  103.0  28.35   
...               ...           ...       ...      ...    ...    ...    ...   
3223                0             0         0    258.0  123.0   70.0  19.72   
1040                0             1         0    192.0  143.0   98.0  29.01   
1266                0             0         0    220.0  143.0  104.0  29.85   
264                 0             1         0    176.0  134.0   97.0  38.14   
1225                0             0         0    137.0  127.0   82.0  27.04   

      heartRate  glucose  
2545       66.0     74.0  
1154       82.0     88.0  
1538       75.0     70.0  
1407       70.0     65.0  
4070      125.0     80.0  
...         ...      ...  
3223       80.0     71.0  
1040       90.0     68.0  
1266       75.0     87.0  
264        68.0     94.0  
1225       60.0     71.0  

[2559 rows x 15 columns]

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
new_xtrain=sc.fit_transform(x_train)
new_xtest=sc.transform(x_test)

In [16]:
new_xtrain

array([[-0.89560743, -0.17683006,  1.96348517, ..., -0.31026879,
        -0.80103611, -0.33457139],
       [-0.89560743, -0.52888513,  0.01824376, ..., -0.06701653,
         0.52166201,  0.24950202],
       [-0.89560743, -0.52888513,  1.96348517, ..., -0.03753141,
        -0.05701842, -0.5014495 ],
       ...,
       [ 1.11656063,  0.99668684, -0.95437694, ...,  0.9870766 ,
        -0.05701842,  0.20778249],
       [ 1.11656063,  0.87933515, -0.95437694, ...,  3.02400715,
        -0.63569885,  0.4998192 ],
       [ 1.11656063, -1.11564357, -0.95437694, ...,  0.29663331,
        -1.29704791, -0.45972997]])

In [17]:
new_xtest

array([[-8.95607434e-01,  1.70079698e+00,  1.82437646e-02, ...,
         2.30653583e+00,  2.00969739e+00, -1.25973740e-01],
       [-8.95607434e-01, -1.70240202e+00,  1.82437646e-02, ...,
        -1.27590655e+00,  1.18301107e+00, -8.42542112e-02],
       [ 1.11656063e+00, -1.35034695e+00,  1.82437646e-02, ...,
        -1.33733389e+00,  3.56324743e-01,  3.32941080e-01],
       ...,
       [ 1.11656063e+00, -2.94181746e-01,  1.96348517e+00, ...,
        -1.64447058e+00, -6.35698848e-01, -3.34571386e-01],
       [ 1.11656063e+00,  4.09928392e-01,  1.96348517e+00, ...,
        -5.43692677e-01, -3.05024318e-01, -5.43169031e-01],
       [-8.95607434e-01, -5.28885126e-01,  9.90864466e-01, ...,
        -4.60151497e-01, -6.35698848e-01, -8.15152972e-04]])

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
lr=LogisticRegression()

In [20]:
lr.fit(new_xtrain,y_train)

LogisticRegression()

In [21]:
y_pred=lr.predict(new_xtest)

In [23]:
from sklearn.metrics import classification_report

In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.99      0.92       942
           1       0.56      0.10      0.16       155

    accuracy                           0.86      1097
   macro avg       0.71      0.54      0.54      1097
weighted avg       0.82      0.86      0.82      1097



In [25]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[930  12]
 [140  15]]


In [26]:
from sklearn.metrics import accuracy_score
print('Accuracy =' ,accuracy_score(y_test,y_pred))

Accuracy = 0.8614402917046491
